#+TITLE: A Primer

This is largely an aid to my own memory so bear with me.

* The Syntax
  I'll start by describing the syntax. Not because it's the most important nor
  the best place to start, but because it's the first thing you see.

  The syntax is, for the most part, inspired by Clojure. In particular, the
  literal data structures: =[]=, ={}=, & =#{}= mean what you expect.

  One major goal is that if an expression *looks* familiar, then it should act in
  a familiar way. The degree to which I've met that goal is an open question,
  but things are still in flux.

  #+BEGIN_SRC clojure
    (def f (fn [x y] (+ x y)))
    ;; ⇒ f

    (f 4 5)
    ;; ⇒ 9

    (if (< (f x y) 0) (g x) (h y))
  #+END_SRC

  and so on.
** Pairs vs Cons Cells
   I wanted to avoid cons cells entirely in this language, but I'm starting to
   realise why they're important: the symmetry between calling a function as (f
   x y z) and defining it as (fn [x y z] ...). The fact that the tail of the
   cons cell (f x y z) is the cons cell (x y z) makes this automatic. So... if
   I want to be able to call things with a single arg that isn't necessarily a
   list, I need improper cons cells. Once we have that, the convention of
   multiple args becomes automatic.

   That said, there are no cons *lists*. The linked list was once a great idea,
   but is, on modern hardware, just about the worst possible way to store
   data.

   Lisp uses cons lists in two ways: 1) as lists of data, for which we'll just
   use vectors, and 2) as a syntax for invoking functions.

   (f x y z) means eval the head =f=, eval (evlis) the tail =(x y z)=, then
   apply the latter to the former.

   We will keep the (f x y z) syntax for calling functions, but instead of
   (cons f (cons x (cons y (cons z nil)))), we store it as (pair f [x y z]).

   This (f x y z) is identical to (f . [x y z]).

   The =.= can be interpreted in a functional sense as =apply=, or in an actor
   sense as =send=. It turns out they're both equivalent with the right
   underlying abstractions.
** No Implicit Evaluation
   In constrast to most lisps (in fact all I've ever found save one called
   [[https://web.cs.wpi.edu/~jshutt/kernel.html][Kernel]]), we have no implicit evaluation. That means that both arguments and
   return values are passed by name[fn:1]. That sounds crazy. If not for the Kernel
   thesis I'd never have believed such a scheme could work, but it does!

   To explain, I'll need to jump ahead to μ.
** The μ Operator
   Why μ? Two reasons.

   1) it's the next letter after λ.
   2) It looks weird, and I want things that don't act as expected to look
      abnormal.

   μ binds values to symbols, thus extending the lexical environment of its
   body. But it doesn't *do* anything with that body; it's purely syntactic.

   Example:

   #+BEGIN_SRC clojure
     (def f (μ [x y] (+ x y)))
     ;; ⇒ f

     (f 4 5)
     ;; ⇒ (+ x y)

     ;; That is, the pair whose head is the symbol `+` and whose tail is the
     ;; vector of *symbols* `[x y]`. The symbols x and y are bound to 4 and 5
     ;; respectively, but we're still trying to add symbols, rather than their
     ;; referrents, which is an error.
   #+END_SRC

   μ doesn't define a macro. A μ is first class: they can be passed and returned
   as values, they operate at runtime (or compile time, or anytime).

   But a μ has no direct access to the environment (nor the continuations). You
   can pass a namespace to a μ (it's just a map) and take it apart so as to
   perform any reflective feat your heart may desire, but the lexical environment
   of an expression is immutable and the expression must be redefined to change
   it, so there's nothing that can be done by the body of a μ with its own
   lexical environment.

   Also remember that macros evaluate their own output (or properly speaking the
   compiler expands the macro and then calls =eval= on the result), whereas μs do
   not.

   But if nothing evaluates the output of a μ, how do they *do* anything?
** Immediate Evaluation
   The answer to the hanging question of the last section is that there is a
   syntactic expression that "means" =eval=.

   In reality it means "evaluate the following expression as soon as you have
   all of the information required to do so", which will remain ambiguous until
   we get into the details of the AST.

   That syntax is the tilde =~=.

   #+BEGIN_SRC clojure
     (def f (μ [x y] (+ ~x ~y)))
     ;; ⇒ f

     (f 4 5)
     ;; ⇒ (+ 4 5)

     ;; `~x` and `~y` can be evaluated as soon as `f` is called. Since they're
     ;; bound in the lexical environment of the body, eval reduces to lookup.
     ;; But remember that the output is not evaluated, so `f` returns an expression.

     (def g (μ [x y] ~(+ x y)))
     ;; ⇒ g

     (g 4 5)
     ;; ⇒ 9

     ;; Note that this only works because `+` is defined so as to eval its
     ;; arguments before applying the underlying addition operation.
   #+END_SRC

   Given a function that only works on literal values (say a version of =+=
   called =+*=), we can define an operator =wrap= which will invoke it in the
   standard applicative manner by first evaluating its arguments:

   #+BEGIN_SRC clojure
     (def wrap
       (μ f
          ~(μ args
              ~(~f . ~~args))))

     (def + (wrap . +*))
   #+END_SRC

   We can even define λ (here called =fn=) as a μ which receives arguments,
   evaluates them, passes the evaluated values to another μ and then evaluates
   its output:

   #+BEGIN_SRC clojure
     (def fn
       (μ [params body]
          ~(μ args
              ~((μ ~params ~~body) . ~~args))))
   #+END_SRC

   This is almost the definition of =fn= at the core of the language (there's
   book keeping around destructuring, docstrings, etc. which I won't go over
   here).

   It may help to think of the body of a μ as quasiquoted, except that we can
   unquote as many times as we please.

   That said, none of quote, unquote, quasiquote, eval, nor apply are defined as
   operators in the language — you can easily write them yourself, but please
   don't — so the analogy is a bit weak.

   The key hurdle in understanding this is that the core operators which in the
   usual course of things ~define~ lisp — that is =eval= and =apply= — are, in
   this language, part of the syntax. Because you can't "call" eval at runtime,
   we don't have to worry about Wand's triviality of fexprs: we always know
   exactly what will and will not be evaluated. We actually have much more scope
   for compiler optimisations than typical languages, but that's a whole other
   discussion.
** An Exception
   One final note: I said above that there is *no* implicit evaluation. You've
   probably noticed in my examples that everything typed into the repl *is*
   automatically evaluated. The same holds for the code reader =loadfile=. This
   is a convenience that once again makes code that acts as expected look
   normal. Also there's no point entering code into a repl unless you want it to
   be evaluated, so it seems like the right thing to do.

   μs are, of course, free to evaluate their arguments when and as they see fit.
   =def= adds an evaluation to the beginning of its body, for instance. I think
   that's the right thing to do as well, but it adds a bit of asymmetry to the
   definition of metaprogramming operations like =fn= and =wrap=.
* Reduction and the AST
  As covered in the previous section, whether or not an expression will ever be
  evaluated — that is whether a given expression is code or data — is expressed
  syntactically. Given =(f x)= the question of whether =x= will or will not be
  evaluated doesn't depend on the *type* of =f=, but on its syntactic structure.

  Syntax is topological. But it has no notion of time. The question of *whether*
  an expression will be evaluated is syntactic, but the question of *when* an
  expression will be evaluated is contextual: it depends on the unknowns in the
  expression and on whoever provides them, not to mention system load and other
  factors external to the expression itself.

  Take for example, the humble =λ=. Copying from above, we have:

   #+BEGIN_SRC clojure
   (def fn
     (μ [params body]
        ~(μ args
            ~((μ ~params ~~body) . ~~args))))
   #+END_SRC

   Notice that everything here is a symbol, even =def= and =μ=. This expression
   can only be evaluated in an environment that provides meaning for those
   symbols. And yes, you can override them if you want to. You can also rebind
   =self-insert-command= if you feel like it.

   Some notes on abstract syntax: =(f x y)= is a Pair, in our parlance. The head
   is the ~symbol~ =f= and the tail is the list (of symbols) =[x y]=.

   A Pair is just data. It doesn't represent a function application. An
   Application is represented by =#(...)= to distinguish it from a pair.

   =#(f x y)= represents the application of =[x y]= to the *symbol* =f=, which
   is senseless and would result in error.

   In a traditional lisp, we have
   =(eval (f . tail))= ⇒ =(apply (eval f) (map eval tail))=.

   But we aren't writing an applicative language, so we want something more
   like:

   =(eval (f . tail))= ⇒ =(apply (eval f) tail)=

   Which is represented syntactically by our first rule:

   =~(f . tail)= ⇒ =#(~f . tail)=

   Thus ~(f x y) -> #(~f x y) which applies [x y] to whatever the symbol =f= is
   bound to. The μ to which f is bound might in turn choose to evaluate (lookup)
   x and y to do something with them.

   The second thing we need to do is create actual μ objects. I don't believe
   its possible to implement μ in this language, so we need an escape hatch
   to define primitives.

   Let =μ= be bound to the primitive =#F[μ]= — =#F= denotes "primitive function"
   even though they aren't always functions, it's a legacy name that might
   change one day — then we have

   =~(μ params body)= ⇒ =#(#F[μ] params body)=

   which causes the underlying implementation of the primitive =μ= to be
   called with the tail of the application: =[params body]=.

   It's up to a primitive to continue the evaluation appropriately, which makes
   them somewhat brittle. The vast majority of primitives simply expect literal
   values and never evaluate their arguments. Only a small minority need to
   manipulate their arguments as sexps. Those are all related to creating and
   manipulating structures which are outside of the scope of the syntax.

   There are also primitive functions which can only be applied to literal
   values. These aren't essential to having a working language, but while you
   could implement arithmetic lambda calculus style, it's advisable to wrap the
   machine's arithmetic capabilities (or those of the implementation language at
   least).

   Primitives are best thought of as interpreters implemented in another
   language with which we communicate via messages. But more on that later.

   Our third rule of execution involves what it means to apply arguments to a μ.

   If we let =(#μ params body)= represent an actual μ object with =params= and
   =body=, then we can write:

   =#((#μ params body) . args)= ⇒
   =(extend-enviroment (destructuring-bind params args) body)=

   Note that =extend-environment= and =destructuring-bind= are
   oversimplifications for didactic purposes. We'll explain later how
   environments really work.

   This is just Steele's "λ the ultimate declarative" without applicative
   semantics. A μ takes arguments, binds them to formal parameters, and then
   reduces its body in the new, extended environment.

   N.B.: "reduction" in this context refers to applying the rules we're laying
   down. They simplify an expression without necessarily evaluating it. If
   there's sufficient information, then reduction will fully interpret an
   expression, but in general there will be arguments that aren't known yet.

   There's a special case of applying arguments which is just β-reduction:

   =#((#μ X Y) . ~Z)= (where X, Y, & Z stand for subexpressions)

   becomes Y with symbols occuring in X renamed to their bindings in Z.

   In particular =#((#μ X Y) . ~X)= ⇒ =Y=. This actually comes up often as an
   optimisation, so it's useful to recognise.

   Finally, eval distributes over collections, and literal values are fixed
   points to eval.

   That is: =~V= ⇒ =V= if V is a literal value (number, string, bool, etc.)

   and: =~[X Y Z ...]= ⇒ =[~X ~Y ~Z ...]=, =~{X Y ...}= ⇒ ={~X ~Y ...}=, &c.

   N.B.: The interpreter is currently written to explicitly walk the ast and
   apply rules. the =core/rules= map defines the rules currently needed which is
   larger than those discussed above.
** Summary
   - Note taken on [2025-05-13 Tue 15:22] \\
     This section is likely out of sync with reality.
   Reduction is the process of applying the following rules repeatedly until
   none can be applied any longer:

   An expression is considered "fully reduced" if it contains no immediate or
   application nodes.

   1) ~(X . Y) ⇌ #(~X . Y)
   2) #(#F[f] . tail) ⇒ always escapes to implementation
   4) #((#μ X Y) . Z) ⇒ Y in the current lexical env extended by {X Z}
      where {X Z} represents the destructured binding of X to Z

      The essentially says the ~X inside Y means Z.
   5) #((#μ X Y) . ~Z) ⇒ Y with {X Z} as a renaming mask
      If ~X means ~Z then use of X stands for use of Z.

      The special case Z=X makes this a noop.
   6) ~V ⇌ V whenever V is a literal value
   7) ~[X Y ...] ⇌ [~X ~Y ...]
      Similar rules apply to maps and sets in the obvious fashion.

   Some of these rules are reversable, some are not because information is lost.

   The order in which these rules are applied is irrelevant since all
   permutations will result in the same final state (possibly with some
   backtracking over the reversible rules, I'm not sure).

   I have a handwavy proof that validates my intuition regarding the previous
   assertion, so be skeptical.

   This (indirectly) answers the question of when an immediate expression gets
   evaluated. By following the rules from a valid input, you will always end up
   at a value. That value might be a μ waiting on arguments. Obviously the
   interior of that μ will be blocked to some extent until those arguments are
   known.
* The Environment
  The core semantics of the environment are based on Scheme. Or more
  specifically on an adamantly lexically scoped version of scheme, the downsides
  of which were explained in "the art of the interpreter".

  To paraphrase that paper, lexical scoping "All the way up" results in a
  strictly one pass interpreter where forward declarations and recursion (both
  simple and mutual) are impossible because nothing can refer to anything that
  didn't exist strictly before it does (including the form itself), Also
  debugging is very hard if you can't redefine things and see what changes.

  I haven't made these problems go away — they're not going anywhere — I just
  think priorities have shifted and the evidence of the benefits to be had from
  immutability makes some pain worthwhile.

  Firstly, computers are orders of magnitude faster than they were 50 years ago.
  We don't need to change anything in place if we can recompile an entire
  namespace in 100ms.

  I also cheat by allowing a namespace to include "declarations" as part of its
  definition and anything declared will, when evaluated, just postpone the
  computation until it has been defined properly. Notably, named functions
  declare their own names when created, so recursion works as expected.

  Where we diverge from scheme, and all other lisps with which I'm familiar, is
  in where the environment is stored and how it is managed.

  The interpreter does not pass the environment around. Rather the environment
  in which a sexp is to be interpreted is part of the sexp itself.

  When a μ is created, we transform its body by tagging all uses of its
  parameter. This is currently called "capturing", but that might change.

  Similarly when a μ is invoked with arguments the body is again transformed,
  this time replacing captured symbols with symbols bound to the passed
  arguments.

  We don't necessarily know (yet) if a symbol will be evaluated. But we know
  exactly what it will evaluate to when and if it is.

  References to symbols imported into the current namespace work similarly. You
  can think of a μ defined in a namespace as a being passed a namespace as well
  as its arguments. The version of the namespace passed is fixed statically, so
  we always know exactly what we're calling. But having the expected namespace
  version separated like that makes propagating changes much less painful in the
  face of an immutable code base.

  This isn't how it's actually implemented at present, but I find that way of
  thinking about it helpful enough that I might move the implementation in that
  direction as things mature.

  What we gain from this admittedly large dose of complexity, is a stateless
  interpreter. The meaning of every form is contained in the form itself.
  Reference is static but code doesn't have to be linked at compile time. Thus
  we still get the benefits of shared libraries (if multiple things are using
  the same version of the same library), without the typical pain of multiple
  programs running at the same time but expecting different versions of the same
  shared lib. Imagine maintaining a linux distro where shared lib version
  conflicts don't exist...

  During reduction when we create a new form to be acted upon later, we also
  create and attach its environment so that when (if) it is eventually evaluated
  that environment will determine its behaviour.

  That makes the environment immutable. So much so that we can pass arguments to
  a function without evaluating them knowing that when they are (eventually)
  evaluated, it will be done so in the correct context.

  This has a number of ramifications, not the least of which is that lexical
  capture is impossible since meaning is part of the form being manipulated.
  This is in contrast to lisp where the meaning of a symbol is part of the state
  of the interpreter (the environment) and so when a statement gets evaluated
  can change what it means. Thus we don't need hygienic macros.

  But even though metaprogramming is safer and first class, it's still often
  difficult to get right. So judicious is still required.
* Pipes, Channels, and Streams
  In this language channels and streams are two sides of the same phenomenon.
  I'm calling that phenomenon a pipe for lack of creative inspiration.

  Channels are black boxes to which messages are sent. They take the place of
  addresses in actor languages or objects in OO languages. They act similarly to
  write only channels in a CSP style language.

  A stream is a lazy, potentially unbounded, sequential data structure. A stream
  is a value, but it might not yet be known. Reading the first element off of a
  stream will return it if it is known right now, or it will park and wait for a
  value if it isn't. Calling =rest= on a stream returns the stream consisting of
  all but the first element and never parks.

  A pipe consists of one stream and one channel. Writes to the channel realise
  the next element of the stream. Thus calling =first= on a stream is equivalent
  to taking from a channel in CSP, except that it will only park once; further
  calls will just return the known value. Calling =rest= on a stream returns a
  new stream which just ignores the first message sent to the channel.

  Importantly, if we retain the head of a stream, then the entire thing will be
  realised into memory. If we throw away the head and pass the tail, then we are
  effectively iterating over messages on a channel.

  When a message is sent on a channel, the corresponding stream caches it since
  it may not be possible (or safe) to recompute it.

  Sending a message to a channel where no one is reading the corresponding
  stream will also park. This provides backpressure on emissions and lets the
  runtime know that all messages sent from a given μ have been received before
  cleaning up and moving on.

  Default (syntactic) return, under the hood, emits to a channel named :return.
  :return is always a channel and so anything that can return really has a
  return ~stream~, not a return ~value~. But having to read the first element of
  the return stream every time a subprocess is invoked is painful and error
  prone.

  So a convention: application of a μ to arguments creates a return channel,
  sets up the computation and returns the first value from the return stream to
  the syntactic return position. The return stream can be retrieved as a
  stream using the aptly named =return-stream= operator. This is necessary both
  for callers that want to use multiple return values in the old lisp sense, as
  well as callers who want to treat the stream of return values as a signal to
  process and pass on (generally via multiple return values).

  These are my current thoughts on the matter but might change. As always.

  A pipe isn't actually a reified thing in the language as yet. The =pipe= fn
  returns a pair [stream channel]. I just want to stop using the clunky term
  "channel-stream pair" all over the place.

  Curiously, streams have no way of knowing from which channel it is that they
  get their values. They simply don't need to; just what the values are and when
  no more are coming. This might have security implications. You can't leak what
  you don't know, after all.
* The Continuation Map and Emission
  One of the bigger differences between this language and standard lisp (or any
  von neumann style language with which I'm familiar) is that there is no single
  "current continuation", but instead a set of them. And control can pass to any
  number of them from the current expression. It can even pass to several of
  them concurrently and several times each at that.

  This is not too different from an actor system, but messages are always sent
  in batches from tail position. The continuation map is akin to Erlang's
  "address book", but it's aggressively local and indirected. You can't send
  messages to named things, you send messages on named channels (whose name you
  choose), and something above you in the call graph binds those names to actual
  channels.

  The underlying theory comes from what Koestler called holarchy which is the
  idea that each unit is autonomous from its own point of view: it can set up
  subcomputations and connect the results of those to channels, but it's
  simultaneously subordinate to higher levels in that it doesn't ultimately know
  how its outputs will be used, nor whence its inputs come.

  A more programming friendly metaphor: Pure functions can't do anything at the
  end of the day. That's why we needed monads before we could create Haskell.

  Do blocks (progn for the die hard lispers) exist because we generally want our
  code to do things other than compute and return answers. These side effects
  are the source of all kinds of complexity. We can't live without them, but oh
  boy.

  So I've made a change to the traditional structure: there are no progns.
  Function arguments are not evaluated in order. You can't control the sequence
  in which things happen at all. All you can do is establish data dependencies
  between computations and then send batches of messages.

  So if you want to add logging to a program, you can't just stick in a
  statement and have a side effect coming from nowhere. But you can intercept a
  batch of messages and add one more message to be sent to a logging channel.

  So we can still perform side effects, but those side effects must exist as
  pure data (messages) sent to the things that actually bang on the world. Those
  messages can be logged, replayed, or even filtered. That makes a big
  difference.

  The continuation map doesn't exist as a first class thing from within the
  language. Rather it is maintained by the runtime and can be modified in a
  limited fashion — using =with-channels= or =capture= at present; I conjecture
  that that's sufficient, but we'll see. I don't want to write code in cps if I
  can avoid it.

  When a batch of messages are emitted, they are all delivered (logically
  speaking) concurrently. If there's enough spare compute, they'll be delivered
  (execute) in parallel, otherwise they get queued. See the section on work
  stealing for details. Not being able to depend on order of delivery saves us a
  world of pain when it comes to starvation and race conditions.

  The only guarantees we make on delivery are

  1) messages are delivered strictly after they are sent
  2) multiple messages sent from A to B are delivered exactly once and in order
  3) receipt of messages can be verified

  Note that if A and C both send messages to B, then those streams can be
  interleaved in any fashion, but the subsets from A and C will be in the order
  sent.

  These are the only guarantees we can provide without pretending special
  relativity doesn't apply to us. For better or for worse, it does apply to us.

  These are essentially the guarantees of TCP. That wasn't intended originally,
  but isn't surprising in retrospect.

  In essence, a fully consistent totally ordered view of the world is only
  possible from a single point in space. Once you have multiple actors in
  different locations, perspective becomes an irreducible aspect of the system.

  So if you want a consistent view, put messages in a queue and process them in
  serial. It's not that hard.
* Ordering
  I said above that you can't control the order in which things happen. Of
  course if that were strictly true you wouldn't be able to coordinate anything.

  All processing that is ready to happen happens concurrently. But sometimes we
  need to ensure that one batch of messages will be received before a second
  batch is sent. This is where the =seq= construct comes in.

  =seq= is like =do= (remember I said we don't have a =do=?) except that it
  doesn't constrain the order in which computations happen. The only guarantee
  it makes is that if t₁ preceeds t₂ in a seq, then all messages emitted by t₁
  must be delivered (received) before any messages emitted by t₂ are sent. This
  applies even if t₁ and t₂ don't share any emission channels. We'll see why
  that's necessary when we get to reduction and local state.

  The distinction between when computations happen and when emissions happen is
  important because emissions in this system are just data which can be
  "returned" without actually posting messages to channels until the appropriate
  time.

  Since delivery of messages is, in general, an inexpensive operation compared
  to the computation which determines which message to send this gives us a
  natural way to exploit parallel hardware.

  Previously there existed a =conc= construct which was like =seq= but
  explicitely parallel. But I'm no longer confident that that's useful.
  *Everything* should be concurrent unless otherwise specified. Mostly it is
  concurrent, but data dependencies control the order in which things happen.
  With =seq= we can control the order in which batches of messages are sent, but
  again not the order in which those batches are computed.

  So =conc= is the default and thus not needed. But now I've gone an broken work
  stealing because I no longer have a nice queue of "things to be done".

  Do I need to go over the interpreter and figure out which parts can be lead to
  forking? I'm pretty sure the only place that would be is =walk-coll=, which
  gets called a lot, but is ultimately just a wrapper around =map=.

  So maybe I just treat each =seq= as a fork-join point. But what about places
  where the order of message emission really doesn't matter? Doesn't matter to
  whom? Can we ever be sure it matters to no one?
* Stateful computation
  Sometimes a computation needs to retain state across messages. Given that we
  have no mechanism by which to assign or mutate, how do we accomplish that?

  The easiest way would be to have a unit which from tail position sends messages
  to its future self (plus whatever emissions it needs to make).

  And that's exactly what we do, but we have to do some more work to make sure
  that our messages to ourself align properly with the input:

  #+BEGIN_SRC clojure
    (defn reduce [rf init xs]
      (let [[state state-ch] (pipe init)]
        (net
         (with-channels {:return state-ch}
           (map rf state xs))
         (last state))))
  #+END_SRC

  =map= takes to elements of each of its input streams one at a time, so by
  priming =state= with an initial value, we can ensure that it's always one step
  ahead of the input stream =xs=.

  We're back at clojure's initial lazy seq api which works so well with the
  =->>= macro. We could overload map, filter, etc, and have transducer syntax,
  but there's no longer any benefit since we get both laziness and fusion from
  the language guarantees. We can always call =into= to get a vector fully
  realised in memory. By themselves, map, filter, etc. return ~streams~ which
  may not be realised (i.e. may park when you try to read values) and which are
  not intended as random access datastructures.

* Outline
  Sections to be written.
** History, Environment, and Context
   I gave a [[https://www.youtube.com/watch?v=Kgw9fblSOx4][talk]] on some of these ideas a long time ago. My opinions on the
   benefits haven't changed, but I've found better ways to implement them.

   You can only have unique permalinks without global concensus if:

   1) You and the link author share some context
      At the very least you have to look in the right place.
   2) The links can grow in size arbitrarily
      Fixed size hashes will eventually lead to collision. I don't care how few
      atoms there are in the observable universe.
   3) Divergences can be converged without consulting either author
      If two people who've never heard of each other publish under the same hash
      at roughly the same time, anyone who knows of both must be able to
      "decorrupt" the hashmap by themselves in a way that anyone else with whom
      they communicate can understand and replicate. The original authors might
      be lightyears away so they cannot be relied upon. Even if they're right
      here, they can't be relied upon to agree.

   None of those criteria have anything to do with hashes.

   Hashes are useful for their concision and cease to be beneficial when you
   start to need sha512 to guarantee uniqueness.

   Using large hashes makes microreferences infeasible for the same reason that
   credit card fees make microtransactions infeasible.

   It turns out that if you keep a history of edits going all the way back to
   the beginning of the web, then you and the person you're sending to (or
   receiving from) can always go back to a shared context and regrow from there.

   In general you don't even need to go back very far if you communicate with
   this other person frequently.

   So my approach is to never throw away history. Spool it out to disk or other
   durable storage if you don't need it in ram (and you don't, mostly) but don't
   throw it away.

   Some sort of compression will be required eventually. Kafka has a decent
   model for this. But it's critical that we only squash linear sequences and
   don't remove branching from the network, otherwise we'll lose recombination
   down the line.

   There's utility in keeping the history of every keystroke in your editor.
   That utility becomes a liability when publishing. The published history of
   your work should be a sample from the tree of edits you've made. Meta data
   might need to change, but the structure will have to be preserved.

   You ought to keep your superset of your published work for posterity (or
   yourself). It's surprising what you can learn about your own thought process
   by watching your keystrokes played back to you in real time.

   Archives and anthologies can in turn be coarser samplings of published works.
   Again the branching structure needs to be preserved, but details can be
   thrown away where they're not of interest.

   Mathematically these nested compressions form a fractal. Fractals make for
   natural compression algorithms, and the readers of your work will only ever
   need to download a tiny fraction of changes you've made to a blank page over
   your writing career.

   If it isn't obvious, my thinking was skewed by Ted Nelson's work decades ago.
   I don't have direct attributions at hand, but there's more than a little
   Xanadu in the above.

   That doesn't seem like the concern of a language per se. But when you
   consider that telemetry and debugging are mostly about rebuilding context
   that was thrown away for performance reasons, you'll see that it makes sense
   to think about it at the language runtime level as well.

   This is very high level. I'll add the details of how it works in this
   language (environment?) as the prototypes evolve.
** Namespaces
** Transduction
** Message Passing
** JIT and runtime optimisation
   The AST itself is optimisable, large parts can be evaluated immediately, and
   it's fairly fast to interpret at runtime.

   I also want a native compiler. The up side of strict immutability, reentrant
   code, and static reference is that we never have to compile a form more than
   once. The compiled code will always be the same if we compile it the same
   way.

   But that said, we do want to try and compile things in different ways
   depending on profiling during real usage and compare performance (say compile
   both to cpu and gpu and instrument to figure out how much data makes the
   switch worthwhile). But that's just a cache of code plus compiler options.

   My intuition tells me that if we get the static reference right and most code
   never changes (only change code if there's a security vulnerability, or a
   massive and much needed performance improvement) then over time more and more
   code will be compiled in more and more ways so that very little will be
   interpreted and most of the runtime's work will be in applying heuristics to
   choose which compiled code to run on which occasion.

   Hardly a trivial problem, but there's real opportunity here.
** Work stealing
   The work stealing implementation is based on Cilk, but immutability
   simplifies a lot of things.

   When a μ emits messages, they are pushed into the work stack and control
   returns to the main loop. The main loop takes the top item off the stack and
   runs it. If the work stack is empty, then it attempts to steal work from
   another worker.

   The thief randomly shuffles the list of other known workers and tries to
   steal work from each of them until successful.

   When work is stolen, it is stolen from the *bottom* of the (upwards growing)
   stack. This is based on the reasoning that things at the bottom of the stack
   are closer to the root of the computation, will represent more work, and thus
   will minimise steals.

   Unlike cilk, we only need one stack. We don't need to worry about workers
   stepping on each other's caches because everything is immutable, so you can't
   invalidate the cache. Once work is stolen, it and its decendents will be
   executed by the thief unless they are stolen in turn.

   This should help with distribution, but stealing will need to be a bit more
   sophisticated to minimise data transfer over the network.

   One other note: as currently implemented, evaluating a vector of length N
   results in N messages being sent to eval, which can lead to each element
   being evaluated in parallel. Thus we get the auto parallelism of Multilisp
   — where (f x y z) will eval x, y, and z in parallel before applying them to f
   — without the complexity that comes with leaving it up to the programmer to
   ensure order of evaluation doesn't matter.

   We can also get pipeline parallelism automatically in long transduction
   chains, but that's a story for somewhere else.
** Offloading work to GPU
   Most consumer machines have gpus nowadays and a lot of streaming tasks map
   natuarally to them — though many others don't.

   Figuring out which can only be done in general at runtime.

   The plan is to use Vulkan instead of compute centred apis as is normally
   done, because there are vulkan drivers for basically every graphics chip out
   there. Plus you have a lot more flexibility than with cuda or opencl.

   Spirv takes a lot of inspiration from llvm, so code generation doesn't
   require going up to C and back down again as it does with glsl. This is only
   a theoretical benefit and I reserve the right to revile my present self at
   some future date.

   Plus there are a lot of cool things you can do with mesh shaders and ray
   tracers. They aren't just for graphics any more than pixel shaders are. Maybe
   a little bit more.
** Compiler
** FFI / Distributed Execution
   These aren't normally the same thing, but they both boil down to talking to
   other computers, so their solutions largely overlap.
* Preliminary notions
  If you're going to try, go all the way, otherwise don't even start it. — Bukowski

  This is a constantly changing very high level description of the form which
  the thing I'm describing takes. The code is a much better description, but
  that changes too fast.
** Receivers                                                     :receivers:
   A receiver is (surprise!) a thing that receives messages. You might think of
   it as a lambda, but it would be better to think of it as a first class macro,
   but even that isn't quire right. See :reflection: and :metaprogramming: for
   more about that.

   I'm going to use the symbol ν to represent the built in receiver which
   when sent a description of a receiver, produces a new receiver.

   A receiver is a single observer from the point of view of special
   relativity. The only information it gets from the universe are the messages
   sent to it and it gets them in some total order.

   Note that this means that two receivers that receive the same messages from
   the same senders (has to be plural) might receive them in different
   orders. This is a reflection of the physical universe in which they
   operate. There's nothing to be done for it.

   A receiver (logically) processes each message it receives, serially, in the
   order in which they are received. Thus a receiver is effectively a serial
   computation. A linear view of some subset of the universe.

   Of course this may not actually be what happens in the face of optimisations,
   but nothing in the system can be allowed to observe it not happening. For
   example a receiver that receives a message, squares it, and sends the square
   somewhere, can (and should!) be run in parallel on a long stream of input
   messages, but the outputs must be buffered and sent in the correct order so
   that an outside observer can't see an inconsistent ordering of events.

   Some receivers maintain internal state. This makes it hard to parallelise
   their activity. Sometimes it makes it impossible. But stateful units often
   have a periodic character which allows the work graph to be partitioned
   somehow. Whether or not I can actually make use of that remains to be seen.

   A much more reasonable optimisation in the face of stateful receivers is
   pipeline parallelism when the steps are complex enough that communication
   overhead doesn't dominate. This can and should be handled automatically by
   work stealing.

   Notably, receivers are not functions, proceedures, subroutines, etc.. They're
   routines in an old sense of the word. Every receiver terminates in an =emit=
   instruction which basically jumps back to the event loop after setting some
   registers. The use of return stacks is a potential optimisation, but not part
   of the language's control flow.
** Namespaces and Dependencies
   All code exists within a namespace. A namespace must be defined before code
   is written because the namespace is the context in which the symbols in a
   unit of code are to be interpreted.

   N.B.: This makes the Ur namespace something external to the language that has
   to be coded separately — possibly by hand — before the language can be
   bootstrapped.

   Also note that since every tree of namespaces that can be created is created
   by (persistent) modification of the Ur namespace tree, which lets us explore
   the geneology of programs, so to speak, as data via the history. I have no
   idea what the ramifications of this will be, or if they'll be practically
   useful, but it's too novel a point to not mention it.

   There are two basic types of reference to other code:

   1. References to code in external libraries.
   2. References to code within the current project.

   Every reference, of either type, has to be unambiguous and immutable. The
   code to which a symbol refers cannot be changed without changing the context
   of evaluation (namespace).

   An external dependency can be uniquely defined by coordinates (source,
   package, version, symbol), where we think of a source as a location plus a
   signatory (public key), and all artifacts are signed. You could also think of
   a source as a git remote and a version as a signed commit, or tag.

   It is critical that versions are calculated by value, most likely a secure
   hash. They're not just numbers that devs make up (semver).

   Packages aren't a natural thing. They're an abstraction to help us
   organise. Ultimately it's the things symbols point to that have
   versions. I'll refer to a thing referred to by a symbol as a code unit, for
   lack of a better term. It could be a μ or a ν, it could be literal data. I
   don't think there's much else it could be. Of course even a function is sent
   as literal data + context of evaluation (also literal data) + possible
   analysis and compile cache + possible cache of ready to execute binary for a
   given arch.

   The immutability of code units makes caching the outputs of compilers and
   optimisers trivial. All code is jit compiled on the fly, but anything to be
   used in production should ship with a hot cache. The root entry of a shipped
   program is just another immutable code unit, so it should be possible to do
   something like whole program analysis and optimisation on it and still act
   like we're jit compiling (so that everything still works if the user starts
   to edit the code, for instance). This is getting off topic.

   A package is just a (presumably curated) collection of code units by a single
   publisher. A publisher can be an individual or an organisation. But orgs
   don't write code, so a package published by an org is just a collection of
   code units published (internally to the org) by individuals.

   So the real coordinates of an external code unit are (source, symbol,
   version). Packages aren't going away, it's useful to have something organised
   for you by the people who know it best, but they're not primary
   artefacts. They're just pseudo directories. Source code listicles? Well
   there's no shortage of junky packages out there in any ecosystem.

   In theory everything published by a given publisher could be available on an
   à la carte basis. But that'll quickly become a soup of symbols. Documentation
   will be hard to organise. Imports will become insanely verbose. Can't say I
   like that.

   But we're forgetting that extenal dependencies, even if you only depend on
   one symbol, are written within namespaces, just like your code. So under our
   assumptions, the namespace is the natural unit or level of granularity at
   which to group dependencies.

   So we import namespaces from sources, and every symbol in our codebase can be
   uniquely referred to by something like source://namespace.symbol#version.
   Namespaces can be nested arbitrarily, but the source is always required since
   there's no way to police publishers and enforce unique namespace names. Nor
   would I want to. Sources do need to be unique in some way. A domain and a
   public key should suffice for that. But we'll probably need more
   flexibility. Plus a key upgrade scheme.

   In order not to have to refer to sources repeatedly, we can add an
   indirection at the interface of external and internal code units. Essentially
   we would import source://namespace#version as xyz and require that the name
   xyz be unique within our project. We can, of course, ensure that.

   That sounds nice, but I don't know that it's necessary.

* Comparisons
  I don't know how useful these are. Mostly thinking out loud.
** FP
   Immutability? Check. Big check.

   Types? Yes for the machine, no for the programmer. I'm thinking of putting in
   a clos/julia style polymorphism mechanism, but then I'd have to start
   worrying a lot more about types. I'm torn.

   Types in currently trendy languages seem to be all about being more static
   and preferring syntax over semantics. Types are about *shape*, not *meaning*
   and as such they're the same as text in a source file and in the runtime.
   That's a very powerful thing, but I have a generalisation of homoiconicity
   which strikes me as a lot more powerful. And more fun to use.

   Functions? Not really. Mathematical functions can be implemented easily, but
   they're a special case of a more general construct.

   The basic operator of the language, μ, takes one argument (receives one
   message) and sends zero or more messages on each of zero or more channels.
   This is based on Hickey's transduction and on Bird's work on Squiggol, but
   with with convergence and divergence of streams which makes it more powerful
   and more complicated. I still have an algebra though.
** FBP
   I had never heard of FBP until quite recently. Reading Morrison's book (2010)
   makes it clear that a lot of my ideas are not new and have been in use —
   albeit obscurely — for decades.

   Particularly the delivery guarantees of which I was pretty proud. But at
   least I know now that what seemed obviously sufficient has been battle tested
   and does seem to suffice.

   These aren't bad things. I'm not terribly interested in priority. I'm
   interested in making this work and the validation is appreciated.

   That said, there are some important differences between my goals and
   Morrison's description. A lot of those differences come from ideas that are
   relatively new. The idea that immutability can work at scale is not widely
   accepted even today. I doubt it was even conceivable thirty years ago.

   But let's list them out:
*** memory management
    In FBP they take an ownership approach where datagrams must be manually
    allocated and freed. This stems from the fact that each node in the network
    bangs on the memory passed to it.

    I take a different approach in that all messages are immutable. They don't
    need manual management since reference counting suffices. They also don't
    need to be owned, so one unit can send the same message to a dozen others.
    There are other advantages as well.

    The cost of immutability amortises away with isolated mutability.
*** Graphicality
    I'm a big fan of graphical programming, but I don't think it should be
    primary. The primary needs to be machine readable. Machine readability is
    the only way to get widespread interoperability. Short of Lanier's "use ai
    to click buttons as an API" which is very intriguing, but I'm still dubious.

    I contend that being more machine friendly at a low level allows you to be
    more human friendly at a high level. This is mostly because the majority of
    programming language bullshit is about making it easier for the developers
    of the compiler/editor/whatever, and if their job is already easy, they have
    fewer excuses.

    So instead I'm focusing on a traditional language with a (mostly)
    traditional AST, interpreter, and compiler. From that AST we can define
    isomorphisms with both the textual source code (or even multiple textual
    source codes) and a graphical representation.

    So draw your program at a high level and then go in later and tweak the
    code. Or vice versa. Or just stick to whichever you prefer.

    Graphical languages always have a layer of warts between the rubber and the
    road and I don't want that. or is it like studded tires?
*** Fractal Structure
    FBP has an explicitly fractal structure, so if you see a graph of
    components, you can zoom in on any piece and see a nested graph of
    components. This can go on for an indefinite period of time before finally
    bottoming out on something atomic.

    I think there's something fundamentally right about that structure.

    I'm not sure how to encourage it in the current iteration of this language.

    Any set of functions corresponds to what fbp would call the input ports of a
    network. The rest of the network is implicit in the call graph, but that's
    easy enough to follow along and layout on demand.

    So a network could be represented by a map of named functions.

    One major problem is that channels (ports) are not static. They can be
    dynamically generated. It can be, in general, impossible to determine the
    set of possible outputs of such a network statically since it may generate
    functions at runtime and plug them into the network. Technically those
    dynamic plugins would be subnetworks, but I don't know that that makes a
    difference.

    That dynamism isn't something I'm considering stripping from the language.
    That said, most of the time emissions go to named channels and the names are
    easily inferred from the code. There's also the secondary check that
    messages can only be sent on channels in the current context or newly
    generated ones, which gives us some foreknowledge. Likely not enough.
*** Holarchy
    The idea that a network is a whole unto itself in the sense that given
    inputs it does its thing and can't be intereferred with, but simultaneously
    subordinate in the sense that it doesn't control — and doesn't know —
    whence comes its input or whither goes its output, so that its place in the
    larger program is ordained from above, is implicit in what I've read of FBP,
    but never stated as such. Just taken for granted.

    I think — but don't know — that making this explicit by encouraging every
    subnetwork to believe itself to be the entire system will greatly
    facilitate the composition of systems.

    Somewhat hyperbolically, I want a language whose todomvc is kubernetes.
** Squiggol
   TODO: stub

   I've clearly borrowed heavily from squiggol. It wouldn't be unreasonable to
   say that this entire project began as an attempt to create a "natural"
   implementation of squiggol's core concepts, but it's grown far beyond that.
* References
  Some reading that ~might~ help you understand this project:
  - The Act of Creation — Arthur Koestler
  - Steps to an Ecology of Mind — Gregory Bateson
  - Seven Clues to the Origin of Life — A.G. Cairns-Smith
  - Do You Want to Enter the Area? — Charles Bukowski
    If you can't find that, try the posthumously watered down "So You Want to be
    a Writer?".

* Footnotes

[fn:1]
Technically they're passed as forms, not as names. Call by syntax? I don't have
a good word for it. The behaviour is similar enough to call by name for my
purposes I think.
